[package]
name = "blue_sky_service"
version = "0.1.0"
edition = "2021"

[dependencies]
blue_sky_dao = { path = "../blue_sky_dao" }
blue_sky_entity = { path = "../blue_sky_entity" }
sha2 = "0.10"
hex = "0.4"