[package]
name = "blue_sky_web"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
flexi_logger = "0.17"
regex = "1.11.1"
